languageCode = "en-uk"
title = "Room Occupancy Tracking"
theme = "learn"

[params]
brand = "IOT Group3 : Room Occupancy Tracking"
description = "Site showing development process for 3rd Year Software Design Study"
themeVariant = "red"

[outputs]
home = [ "HTML", "RSS", "JSON"]
