languageCode = "en-uk"
title = "Room Occupancy Tracking"
theme = "learn"

[params]
brand = "IOT Group3 : Room Occupancy Tracking"
description = "Site showing development process for 3rd Year Software Design Study"
themeVariant = "red"
showVisitedLinks = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Progress"
url = "/progress"
weight = 30
