languageCode = "en-uk"
baseURL = "sam-barrett.codes/ROT"
title = "Room Occupancy Tracking"
theme = "aether"

[params]
brand = "IOT Group3 : Room Occupancy Tracking"
description = "Site showing development process for 3rd Year Software Design Study"
